server:
  port: 9091
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
